### ISSUE TITLE
apache licensing ?

### ISSUE THREAD

**Issue by sandys** [tomchristie/apistar#111]
hi,
I'm wondering if you would consider using the apache license ? the apache license includes patent grant and which is a huge thing considering that multiple people may end up contributing to your project (as it should be!!)

I would like to link to this hacker news discussion on this topic - https://news.ycombinator.com/item?id=3402450 . You might recognize some of the commenters.

> It depends deeply on the project. Some something like, say, an HTTP API wrapper module, MIT/BSD style licenses are quite sufficient. There shouldn't be something patentable there. Apache, unfortunately, isn't compatible with GPL v2.
> But if you're building something like node.js, nginx, or Lucene, choosing MIT/BSD is likely a terrible idea. Apache gives huge protections for unforeseen scenarios: automatic property rights assignment for contributions, poison-pill–like protections against patent suits, &c.
> I highly recommend this book on Proprietary Information and Open Source: http://www.amazon.com/Intellectual-Property-Open-Source-Protecting/dp/0596517963

- Kenneth Reitz

**Comment by tomchristie** [comment]
I'll consider it yes, although in the meantime if it's genuinely a blocker to any companies they could always request a license grant.
