### ISSUE TITLE
Support string-style type annotations.

### ISSUE THREAD

**Issue by tomchristie** [tomchristie/apistar#116]
We should allow string-literal type annotations to be used in views and in `.build()` methods.

See https://github.com/tomchristie/apistar/pull/114

If you'd like to help progress this issue, one place to start would be to look into the following:

Does python have any helper functions that take a type annotation and coerce any string-literals that are contained within it into class types?

**Comment by frankie567** [comment]
Hi,

I've looked around a bit about this, and found nothing about such helper function. The only thing that *may* help is the [ability to subclass `Signature`](https://docs.python.org/3/library/inspect.html?highlight=inspect#inspect.Signature.from_callable):

```python
import inspect


class MySignature(inspect.Signature):
    @property
    def return_annotation(self):
        return_annotation = super(MySignature, self).return_annotation
        if type(return_annotation) is str:
            #  Retrieve the class in globals dict if the annotation is a string
            return globals()[return_annotation]
        return return_annotation


class DummyClass(object):
    @classmethod
    def __build__(cls) -> 'DummyClass':
        return cls()

inspect.signature(DummyClass.__build__) # <Signature () -> 'DummyClass'>
MySignature.from_callable(DummyClass.__build__)  # <MySignature () -> __main__.DummyClass>
```

However, it raises more problems than it solves:
1. Must replace every occurence of `inspect.signature(func)` by `MySignature.from_callable(func)` which is cumbersome and less self-explanatory (unless to wrap it in a dedicated function?).
2. Doesn't work if the module is not in `globals()` and, as the signature doesn't give us the full class path, it may be hard to load it if not.

Well, that's all I found from my (limited) skills in Python, but I hope it'll bring a basis for reflection.

Best regards!

**Comment by tomchristie** [comment]
Thanks @frankie567. I figure we should just close this off for now.

**Comment by frankie567** [comment]
Sure.

I gave it a shot about properly subclassing and loading the type, and released it as an [experimental library](https://github.com/frankie567/forwardref_inspect). This should work, as long as the forward referenced type is in the same module as the function that references it. Feel free to take a look.

Shame that this issue prevents us from reaching the goal of #87. Let's hope that future versions of Python handle this better!

Best regards!
