### ISSUE TITLE
.env file

### ISSUE THREAD

**Issue by tomchristie** [tomchristie/apistar#118]
We could consider having the `apistar` command read environment from a `.env` file.

**Comment by rcshubhadeep** [comment]
@tomchristie ok if I introduce this dependency - https://github.com/theskumar/python-dotenv ?

**Comment by jpadilla** [comment]
FWI I have [django-dotenv](https://github.com/jpadilla/django-dotenv/blob/master/dotenv.py) which is simple enough for this. Feel free to use any code from there if you want to avoid adding extra deps

**Comment by tomchristie** [comment]
I'm not sure we'd want to pull in everything that `python-dotenv` includes.

I have some reservations about reading .env files from all `apistar` commands, which is why I never got around to including this myself as part of the Environment work.

If you're reading them from any `apistar ...` command then it'd be really easy to fail to notice that your production setup is erroneously reading .env files which you failed to exclude from the repo, and to be unaware that your production config environment *isn't being applied*.

**Comment by tomchristie** [comment]
Can't run into same problem with eg. `heroku local`, or with having an additional external command that sets the config.

We could do something like have an explicit `--envfile` flag on commands, perhaps. Not sure what the best approach is.

**Comment by tomchristie** [comment]
With the explicit flag it's clearer when you deploy to production that you should make sure to exclude that flag from the process.

**Comment by rcshubhadeep** [comment]
I agree with your point. But even then I will say that if that flag is introduced then also we can use the package to read and apply the env variables. It is well maintained and lets us not to re discover the wheel.

What do you think?

**Comment by tomchristie** [comment]
First up is to decide exactly what we do want the behavior to be.
Personally I don't *think* we'd introduce a dependency here, eg. I don't think we'd  the variable interpolation that `python-dotenv` allows for.

**Comment by audiolion** [comment]
The other issue with `python-dotenv` and similar packages is that if you manage your environment in a different way (e.g. shell script that exports variables when you activate your `venv`) you always get warning messages about no `.env` file being found when running commands, otherwise you have to modify the `.env` to be empty

**Comment by tomchristie** [comment]
Thanks @audiolion - reminds me of one of the other issues I had when trying to figure out *exactly* how it should work. Silently allowing an *optional* envfile is a good way for us to introduce unexpected errors. Another nudge towards explicit flags.

I could still go either way on the dependancy.

**Comment by rcshubhadeep** [comment]
ok, let us go back to the basic question first. What do we want to do? When and what the .env is necessary for?

**Comment by rcshubhadeep** [comment]
And one thing to state clearly, I agree completely for the explicit option in the command. This is how it should be

**Comment by tomchristie** [comment]
Closing this off for now. I don't think we necessarily need to bring this feature into the core project, at least at this point in time.
