### ISSUE TITLE
Make ujson opt-in

### ISSUE THREAD

**Issue by renstrom** [tomchristie/apistar#126]
Since https://github.com/tomchristie/apistar/pull/99 was merged, I think it would be a good idea to remove ujson as a required dependency (i.e. part of `install_requires`). It's not really optional if I have to manually uninstall it post-install.

I'm just not a big fan of forcing dependencies for stuff the standard library already covers (and does so well). Especially a C/C++ dependency. Apparently it's not even a drop-in replacement[1]. Seg-faults are also nice[2].

Maybe using `extras_require` in `setup.py` would be a good middle ground, and mention it in the documentation somewhere...?

```python
setup(
    name='apistar',
    ...
    extras_require={
        'maxspeed': ['ujson', 'uvloop'],  # I just mentioned uvloop because of issue #9
    },
)
```

```bash
$ pip3 install apistar[maxspeed]
```

What do you think?

[1] https://github.com/esnme/ultrajson/issues/252
[2] https://github.com/esnme/ultrajson/issues/258

**Comment by tomchristie** [comment]
I absolutely want a minimal install option, yes.

That extends to other packages as well as ujson (eg. we'll probably install Jinja2 by default, but it'd be nice to have an option that avoids that)

I don't want this to be too granular, we should just have "the standard install" and "a minimal install - probably just `werkzeug` and `click`, and install whatever else you happen to need.

My problem with `extras_require` is that I'd really like the standard install to be a wider set of packages, and the optional install case to be the minimal variant. We *could* have `pip install apistar[standard]` but it feels a bit weird.

This environment variable based approach might also work?... https://github.com/channelcat/sanic/blob/master/setup.py#L50

**Comment by audiolion** [comment]
What if it stops the install though?

```
Building wheels for collected packages: apistar, coreapi, ujson, itypes, MarkupSafe
  Running setup.py bdist_wheel for apistar ... done
  Stored in directory: /home/w-daspdp/.cache/pip/wheels/24/89/fc/1a7ad4e150a8cb87641d47aa02e0c27813840ea4711512e8dc
  Running setup.py bdist_wheel for coreapi ... done
  Stored in directory: /home/w-daspdp/.cache/pip/wheels/37/03/ff/1ad3d35cb205faedfb91b8ada05c11970be690e1a0ea1058c5
  Running setup.py bdist_wheel for ujson ... error
  Complete output from command /home/w-daspdp/.virtualenvs/pdp_stage/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-XG4ov5/ujson/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpxbZpI9pip-wheel- --python-tag cp27:
  running bdist_wheel
  running build
  running build_ext
  building 'ujson' extension
  creating build
  creating build/temp.linux-x86_64-2.7
  creating build/temp.linux-x86_64-2.7/python
  creating build/temp.linux-x86_64-2.7/lib
  gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I./python -I./lib -I/usr/include/python2.7 -c ./python/ujson.c -o build/temp.linux-x86_64-2.7/./python/ujson.o -D_GNU_SOURCE
  unable to execute gcc: No such file or directory
  error: command 'gcc' failed with exit status 1

  ----------------------------------------
  Failed building wheel for ujson
```

The `ujson` as part of the required install forces the installing machine to have `gcc`, at least in my case, I don't have access to it (RHEL 7) because sysadmins don't want developers compiling anything they want on their servers.

**Comment by renstrom** [comment]
Thanks for the reply. Standard and minimal sounds like a good approach. I'm just not sure how the minimal installation is supposed to work if the standard installation is the default? Would it just be something like this?

```
$ pip3 install --no-deps apistar
$ pip3 install click werkzeug
```

But that's also two steps, might as well just do `pip3 install apistar && pip3 uninstall usjon` then. But perhaps `pip install apistar[full]` instead of `pip install apistar[standard]` sounds better?

**Comment by tomchristie** [comment]
> I'm also not a huge fan of relying on environment variables to determine how a Python package gets installed.

Yeah fair point really.

**Comment by tomchristie** [comment]
> But perhaps pip install apistar[full] instead of pip install apistar[standard] sounds better?

I like this, yup.

**Comment by audiolion** [comment]
I wish there was a way that if a pip install failed to build a C/C++ it would fall back, like part of the standard install but if it fails its considered optional.

I hate to have `apistar[full]` just because some developers have awful setups, but I can't think of a better way to do it.

**Comment by audiolion** [comment]
Perhaps people who can't / don't want ujson can have a different install path, e.g. `apistar[purepy]` where all c/c++ deps are excluded and for everyone else it is just the normal install

**Comment by renstrom** [comment]
>I hate to have `apistar[full]` just because some developers have awful setups, but I can't think of a better way to do it.

For me it's not so much that my setup is awful, it's that I really don't want to use ujson for various reasons.

>Perhaps people who can't / don't want ujson can have a different install path, e.g. `apistar[purepy]` where all c/c++ deps are excluded and for everyone else it is just the normal install

The problem is that `extras_require` is exactly what its name suggests, *extra* stuff, not less. So using it to install less stuff than the normal install procedure isn't possible.

There's only three possible solutions as I see it:

1. `pip install apistar` installs the bare minimum required to run apistar (i.e. no ujson). And document somewhere that it's possible to manually install some stuff for a faster experience (basically just suggest adding ujson to your own requirements.txt).
2. Same as but offer a `apistar[full]` variant as well.
3. Use environment variables as conditionals as sanic does. I personally don't like this approach.
4. Install everything by default like it's done today and make it the user's problem if they don't happen to have `gcc` available or otherwise don't want all dependencies.

I guess 1 and 2 can (and perhaps should?) be combined.

**Comment by renstrom** [comment]
5. Maintain two different packages on PyPi, one "lite" version, and one regular.

**Comment by tomchristie** [comment]
I really see no reason not to go with 2.

This isn't just about ujson. Stuff like templating and (later) static file support are things we'd want in '[full]' but not in the base install.

**Comment by tomchristie** [comment]
Let's *start* by just dropping ujson, and forcing it to be an explicit install of the user wants it. Docs could mention it in the performance section.
