### ISSUE TITLE
Deploying API Star on AWS Elastic Beanstalk

### ISSUE THREAD

**Issue by maziarz** [tomchristie/apistar#131]
Before even attempting on doing this. Would we assume any challenges in terms of Python support as EB is only supporting Python 3.4?

**Comment by tomchristie** [comment]
> Would we assume any challenges in terms of Python support as EB is only supporting Python 3.4?

Yes. You should. 3.4 doesn't support the type annotation syntax that API Star uses throughout.
Had a quick look around - one thread mentioned installing docker to work around, another mentioned that 3.5 support is due very soon.

Nothing we can do on the framework side to mitigate this - 3.5, 3.6 are our requirements.

**Comment by maziarz** [comment]
I will look into a different solution while i wait for a fully compatible Python 3.5 environment on EB.
