### ISSUE TITLE
compojure-api for python?

### ISSUE THREAD

**Issue by AlJohri** [tomchristie/apistar#133]
Hey, just saw this repo from the monthly report and I thought it was pretty cool. Would you say that this project is sort of like [compojure-api](https://github.com/metosin/compojure-api) for python? It's definitely something I've sorely missed.

**Comment by tomchristie** [comment]
I couldn't really say. 😃 Some of the API schema stuff mentioned there seems a little similar tho, sure.

**Comment by AlJohri** [comment]
Cool :) I'll check it out.
