### ISSUE TITLE
Why API Star

### ISSUE THREAD

**Issue by rmad17** [tomchristie/apistar#149]
Hey guys,
Really nice piece of work here. Really good to see python web servers are improving their benchmarking. However I have got a question. This is my current choice of python web server of choice. 
1. Need Something Powerful and Stable - Django
2. Need something small and simple(May or may not grow in future) - Flask
3. Need to try Async(Never practically did this but I intend to) - Sanic

What would be the scenario where I would use API Star? 

Apologies, if this is not the right place to ask this question.

**Comment by tomchristie** [comment]
Howdy @rmad17, thanks for the question!

We'll probably push open ended discussions towards http://discuss.apistar.org/ in the future, but no problem at all for asking here! (I oughta get a CONTRIBUTING file up).

Ultimately I want API Star to cover all 3 of those bases. We'll be starting to tackle async likely around June/July, and I'd like to build out a similarly powerful set of functionality to Django, but with a more decoupled architecture.

For now where API Star excels is the built-in API Documentation, Schema generation, JavaScript & Python client libraries, and soon-to-land API mocking. You can get a nicely documented API up and running incredibly quickly.

Ask again in a couple of months and I'll probably give you a few more reasons. 😀

**Comment by rmad17** [comment]
Sounds interesting. Maybe I could try to contribute. One further question.
```
I'd like to build out a similarly powerful set of functionality to Django, but with a more decoupled architecture.
```
Right now flask depends a lot on a lot of third party services for making it big. Do you intend to make this a mix of flask and sanic but instead of third party plugins all the plugins will be by API Star.Am I right?

**Comment by tomchristie** [comment]
> instead of third party plugins all the plugins will be by API Star

No, we'll push folks towards creating third party plugins wherever possible, but there's a set of functionality that it's worth us including & supporting in the core package.

For example, I'd like to see SQL Alchemy support & migrations provided and documented directly as part of API Star, but they will still be nicely decoupled & optional. Other backends would likely be third party.
