### ISSUE TITLE
Url encoding on TestClient requests

### ISSUE THREAD

**Issue by marcosfede** [tomchristie/apistar#158]
I'm adding tests and I have some urls with spaces in it. the tests fail because the url parameters are not properly encoded in the handler function. For example I have a handler function that recieves one parameter "time"
`routes.py`
```python
Route('/{time}', 'GET', timestamp)
```

`views.py`
```python
def timestamp(time):
    print(time)
    .... code here
```

`test`
```python
def test_http_request():
    """
    Testing a view, using the test client.
    """
    client = TestClient()
    response = client.get("/December 15, 2015")
```
`time` in `timestamp` function is now `December%2015,%202015` instead of `December 15, 2015`
I've also tried with `client.get("/December%2015,%202015")`

Am I doing something wrong or is this a bug?
Thanks

**Comment by peterj** [comment]
I haven't tried your example, but it looks like you forgot to encode the comma as well:
```
December%2015%2C%202015
```

**Comment by Smotko** [comment]
@marcosfede I believe I fixed your issue with https://github.com/tomchristie/apistar/pull/163 Please confirm :)
