### ISSUE TITLE
Add to TechEmpower benchmarks

### ISSUE THREAD

**Issue by tomchristie** [tomchristie/apistar#18]
See https://github.com/TechEmpower/FrameworkBenchmarks/pull/2633

**Comment by ddorian** [comment]
Can you also include wheezy.web in your benchmark on the readme, please?

**Comment by tomchristie** [comment]
Yeah, tho I'd need to re-run from scratch to make the comparison fair.
Also I *must* include the `wrk` command this time.

This should do:

     wrk -t 10 -c 100 -d 10 http://localhost:5000/

We'll probably change the section in favor of whatever TechEmpower publish if and when that becomes possible.

**Comment by tomchristie** [comment]
Very positive...

> "[API Star was already merged in, so it'll be in the Round 14 final](https://groups.google.com/d/msg/framework-benchmarks/sQDY1uELRkY/58AnGARfBwAJ)"

It wasn't merged in time for us to be in any of the preliminary testing that they run prior to running the final round, so we can't see if they're getting similar results to my testing, or be able to fix any issues that crop up, so just have to cross fingers that all is setup smoothly.

We'll plan to expand the test cases in adequate time for round 15.

Will update the docs once they publish the final round, and close this off. (Should also be able to include wheezy.web then as per @ddorian's suggestion, or simply point to the TechEmpower site)

**Comment by ddorian** [comment]
@tomchristie I only asked for wheezy to be included cause it's been fastest in ~all benchmarks that I've seen it.

**Comment by tomchristie** [comment]
Might also be useful in the future: http://klen.github.io/py-frameworks-bench/

(The remote request case is particular interesting for comparison of async vs sync frameworks)

**Comment by tomchristie** [comment]
Round 14 preliminary results. 👍 

I've filtered to only JS, Py, Go, and Rby results here...

![screen shot 2017-04-20 at 08 59 06](https://cloud.githubusercontent.com/assets/647359/25233744/cdc8ff6a-25d7-11e7-9c47-0583376a73eb.png)

**Comment by tomchristie** [comment]
Round 14 has now been released. Added to the docs

---> https://github.com/tomchristie/apistar#performance
