### ISSUE TITLE
DEBUG Settings / Server errors

### ISSUE THREAD

**Issue by audiolion** [tomchristie/apistar#181]
Hey, just deployed my first API Star server using `Zappa`. An issue I ran into is that I changed a function name in my code and one of my routes tried to call a non-existing function, the result was a traceback returned.

How do I turn off DEBUG? or is this not a debug problem but just an unhandled exception?

This is the traceback that was returned:

```python
Traceback (most recent call last):
  File "/var/task/apistar/app.py", line 93, in func
    state[output] = function(**kwargs)
  File "/var/task/app.py", line 91, in get_all_profiles
    return {k: Profile(v) for (k, v) in scrape_ds_staff_directory().items()}
NameError: name 'scrape_ds_staff_directory' is not defined
```

I have the following in my `app.py`

```python
class Env(environment.Environment):
    properties = {
        'DEBUG': schema.Boolean(default=False),
    }

env = Env()
```

I thought that would do the trick but I am still getting the traceback. Do I need to include the env somewhere? Do I need to pass the setting to my route?

**Comment by tomchristie** [comment]
There's more work still to be done in https://github.com/tomchristie/apistar/issues/6

Right now we're always providing tracebacks for exceptions.

**Comment by audiolion** [comment]
Ah I am a fool, missed that somehow. Thanks, I will close this then
