### ISSUE TITLE
Q: are there any examples in software that use the apistar "components" pattern?

### ISSUE THREAD

**Issue by abetkin** [tomchristie/apistar#190]
Hi everybody! It seems that apistar "components" is a nifty software pattern, that is actually applicable even if a language doesn't have static typing support.

Are there any more examples of that, more or less? In some libraries / frameworks / languages?

**Comment by abetkin** [comment]
probably discuss.apistar.org is a better place for this

**Comment by tomchristie** [comment]
Cross linking: https://discuss.apistar.org/t/components-software-pattern/99
