### ISSUE TITLE
discuss.apistar.org  activate account link problem

### ISSUE THREAD

**Issue by jet10000** [tomchristie/apistar#197]
```
["BAD CSRF"]
```

**Comment by tomchristie** [comment]
I'd suggest refreshing the page and trying again.

**Comment by tomchristie** [comment]
As with #203 if you're still seeing this issue, it'd be great if you could give me a clear step by step walk though of exactly what you're doing so that I have something I can forward on to the discourse team.

**Comment by tomchristie** [comment]
Could be this?... https://meta.discourse.org/t/solved-bad-csrf-on-attempted-login-issue-with-lastpass-and-discourse/51848

(Interaction with LassPass?)
