### ISSUE TITLE
/u/active-account BAD-CSRF error

### ISSUE THREAD

**Issue by tweenietomatoes** [tomchristie/apistar#203]
Pleazzo fixenetti de la "discuss.apistar.org/u/active-account" iz givingos ["BAD CSRF"]
I cannotto activatos meine akkountti.

**Comment by tomchristie** [comment]
I don't see the same issue at https://discuss.apistar.org/
If someone can give me a clear step by step walk through of exactly what you're trying, ideally with screenshots, then I can forward it on to the discourse team.
