### ISSUE TITLE
Explicit extra dependecies

### ISSUE THREAD

**Issue by ewjoachim** [tomchristie/apistar#205]
It's a bit of the following of #126, but as we're starting to have quite a few optional dependencies, it might be useful to explicit them in setup.py (or have a summary somewhere in the doc)

My guess would currently be something along the lines of :
```python
extras_require={
        # supported external orms (choose one)
        'django':  ['django'],
        'sqlalchemy': ['sqlalchemy'],

        # exporting the API schema (choose one)
        'swagger': ['openapi-codec'],
        'raml': ['raml-codec'],

        # faster json (de-)serialization
        'ujson': ['ujson'],

        # production
        'production': ['gunicorn', 'meinheld']
}
```
All of those are mentioned in the doc.

The remaining questions would be :
- [ ] What would a "full" install be (which orm ? which API schema codec ? ...)
- [ ] gunicorn and meinheld are not imported in the code, they're not requirements in the strict sense. Should they be here ?
- [ ] For the database drivers should we suggest things ? at least postrgesql > psycopg2 ? But it's kind of the role of the orm to do that. For example, `pip install sqlalchemy[postgresql]`. Should we provide a shortcut for postgresql (and maybe sqlite ?) `django-postgresql`/ `sqlachemy-postgresql` ?

I'd like to be able to do `pip install apistar[ujson,django,postgresql,production]` for example.

I'll do a PR if a decision is made :)

**Comment by tomchristie** [comment]
I don't think we can do a great job of answering this yet, as introducing asyncio support is going to change things again. I think it's reasonably likely that we'll want to start farming things out into seperate packages at that point, too.

**Comment by ewjoachim** [comment]
I understand your point. I'm completely ok with closing the issue for now, and maybe re-opening someday when it's clearer (let's not clutter the tracker with un-answerable answers ^^)

Thank you for your answer ! And good luck async'ing the lib :)

**Comment by tomchristie** [comment]
I'm going to close this off for now, but I think it's pretty likely that we'll end up with something like this in the end, yes. The work in https://github.com/tomchristie/apistar/pull/235 is starting to make it possible for us to add alternate framework support, so eg. `pip install apistar[wsgi]`, `pip install apistar[asyncio]`, `pip install apistar[flask]` will likely eventually become a thing.
