### ISSUE TITLE
Support exceptions for all relevant HTTP status codes

### ISSUE THREAD

**Issue by ex-nerd** [tomchristie/apistar#209]
I notice that `exceptions.py` is rather sparse.  It would be nice to have access to the full suite of 4xx and 5xx codes (and probably a few more like 301).

I'm happy to do the legwork for this and submit a PR, but thought there might be reasons why so many were left off, so I'll wait for your reply before doing so.

**Comment by tomchristie** [comment]
We wouldn't want to verbosely include individual exception classes for all possible status codes.

For now we'll just include everything that we need in API Star itself. You can subclass and include your own exceptions in your own codebase if needed.

**Comment by ex-nerd** [comment]
That's why the title says "all relevant" not "all".  It would still be nice to see some like 301 (given you already have 302), along with 401 and 403 that are essential for AuthN/Z.  But maybe you have plans to keep the auth-related codes in whatever eventually gets implemented to describe how auth should be added to services that need it.

Anyway, is it still worth documenting the expectation that people subclass the exceptions as appropriate?

(There's also 201, but that's not really an exception and is probably better handled elsewhere, possibly even automatically)

**Comment by tomchristie** [comment]
Righty, that makes more sense.
The set of status codes that we have covered in Django REST framework would be a good baseline.
