### ISSUE TITLE
Doc: please show I/O blocking calls strategy

### ISSUE THREAD

**Issue by sglebs** [tomchristie/apistar#213]
Please add a simple section to the documentation showing how an API which has to go to the database should be done to avoid full blocking. Can gevent & its monkey patching be used? Or should the Python 3 mechanism of async/await be used? Or can either the used, based on the developer's preference? Thanks.

**Comment by sglebs** [comment]
Maybe just a note saying that Meinheld supports some monkey patching, and point at https://github.com/mopemope/meinheld#patching

Also: pls mention whether apistar be used with gevent instead of meinheld. Thanks.

**Comment by tomchristie** [comment]
We're working towards asyncio support now. Docs will be updated once that's all fully in place.

**Comment by tomchristie** [comment]
Related: https://github.com/tomchristie/uvicorn / https://groups.google.com/forum/#!topic/django-developers/_314PGl3Ao0
