### ISSUE TITLE
Replace current commands mechanism with PyInvoke

### ISSUE THREAD

**Issue by thedrow** [tomchristie/apistar#223]
[PyInvoke](http://www.pyinvoke.org/) is the base library for Fabric 2.0.
It provides task execution, namespacing, posix style command line arguments and a lot more.
In addition, there will be no need to add the commands to the App instance. Importing the commands to your `tasks.py` will make them available.
We can create our own [entrypoint](http://docs.pyinvoke.org/en/latest/concepts/library.html).
Porting our commands to invoke will allow us to import tasks from it's ecosystem that are not apistar specific.

What do you think?

**Comment by tomchristie** [comment]
Looks perfectly decent, but no good reason to put time into switching. click has everything we need.
