### ISSUE TITLE
Debug server with visual studio code

### ISSUE THREAD

**Issue by marcosfede** [tomchristie/apistar#225]
Hello,
Is it possible to start the development server using the python interpreter instead of the apistar executable (i.e something like `python app.py` instead of `apistar run`)
I'm trying to set up the debugger on Visual Studio Code and I'm having trouble attaching it to the dev server, has anyone been able to do this?
Thanks

**Comment by tomchristie** [comment]
We ought to allow calling directly from python, yup.

**Comment by tomchristie** [comment]
0.2 wil support the following...

    if __name__ == '__main__':
        app.main()

https://github.com/tomchristie/apistar/pull/235
