### ISSUE TITLE
RequestData is inserted twice into the pipeline resulting in a timeout

### ISSUE THREAD

**Issue by thedrow** [tomchristie/apistar#232]
I have the following view:
```
def foo(key: String, log_type: String, data: Array):
  pass
```

Removing the `data` argument results in completing the request.
During testing the following exception is raised:
```
werkzeug.exceptions.ClientDisconnected: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
```
Executing the request while running the webserver results in a timeout and a 500 status code without any details.
After investigation, I found out that RequestData is inserted twice into the pipeline.
I have no idea what's causing this behaviour but it's blocking me from completing an API I'm working on.

**Comment by thedrow** [comment]
I found a workaround. You can define a schema.Object with all the properties and it serializes correctly.

**Comment by tomchristie** [comment]
Alright, redesigning the dependency injection in any case, so this issue should fall out once that goes in.

**Comment by ofpiyush** [comment]
@tomchristie Is there a branch I can follow the new DI on?

I need some of it's features for use with CLI.

**Comment by tomchristie** [comment]
You can follow along on the version-0.2 branch. Pretty substantial reworking. Shaping up v nicely. CLI still needs to go back in. More info to follow over next few days.

**Comment by tomchristie** [comment]
See https://github.com/tomchristie/apistar/issues/232

Going to close this off now, since it'll be obsoleted once that's pulled in.
