### ISSUE TITLE
SQLAlchemy, lack of scoped_session

### ISSUE THREAD

**Issue by magnusp** [tomchristie/apistar#234]
Looking at [sqlalchemy_backend.py](https://github.com/tomchristie/apistar/blob/master/apistar/backends/sqlalchemy_backend.py) I see no mention of [scoped_session](http://docs.sqlalchemy.org/en/latest/orm/contextual.html#unitofwork-contextual). If the SQLAlchemy component were to be injected in other components, with them creating sessions without closing them, could lead to connection starvation rather quickly. The component also configures a default pool making this a bit more severe when long running transactions are running.

Is this by design? I admit I'm not completly at home with SQLAlchemy, so I may be misinterpreting the docs.

**Comment by tomchristie** [comment]
Plan is to introduce the session as a context-managed object.
This first requires that our dependency injection supports context managers.
Work is coming along in https://github.com/encode/dependency/ which will allow us to support this in due course.
