### ISSUE TITLE
mysql-python is not python3 compatible

### ISSUE THREAD

**Issue by brumar** [tomchristie/apistar#237]
In the readme, mysql-python is suggested as a mysql driver. However, it's not ported to python 3 yet ([reference](https://pypi.python.org/pypi/MySQL-python/1.2.5)). 

I installed `pymysql` instead, changed the prefix to `mysql+pymysql://...` and it worked well. At least I could create the table given in example. I guess the readme could be updated with this suggestion ?

**Comment by tomchristie** [comment]
> I guess the readme could be updated with this suggestion?

That sounds pretty reasonable yup. A pull request for that from anyone would be most welcome.
