### ISSUE TITLE
Slack / Discourse

### ISSUE THREAD

**Issue by tomchristie** [tomchristie/apistar#25]
Use [slack.in](https://github.com/rauchg/slackin).
Could be just one channel, under "Encode" org?

Prefered option for ongoing conversations is probably Discourse... https://www.discourse.org/

**Comment by auvipy** [comment]
yes

**Comment by maziarz** [comment]
A Slack channel would be awesome!

**Comment by auvipy** [comment]
discourse

**Comment by tomchristie** [comment]
🌟 ➡  http://discuss.apistar.org/ ⬅ 🌟

**Comment by tomchristie** [comment]
Alrighty, that's live, and linked from the README.

I've got a few topics that I'll be kicking things off with. Please do feel free to kick off new threads on "What I want to see in API Star", "Pain points I currently have with API development", or any general conversations or questions you'd like to pitch, that don't quite fit into the issue tracker.

**Comment by maziarz** [comment]
Will you be considering a slack channel as well? 💃

**Comment by tomchristie** [comment]
Not right now, no. Perhaps later tho.
The big thing we'd lose with slack is that it's not a public, linkable space.
When we have discussions over on discuss.apistar.org we'll be able to share those, link to them from issues, have folks find them through google, etc.etc.

Clearly there *is* also value in having a realtime discussion format, but I think I'd like to leaving considering that for a slightly later day. Feel free to ask again in 3 months time and I might take a different view and say "Yup let's do it now!" 😎
