### ISSUE TITLE
Debug server reload after code changes

### ISSUE THREAD

**Issue by sylwekb** [tomchristie/apistar#40]
Add similar to django local dev server restart on source files changes

**Comment by tomchristie** [comment]
Yup, we may do. Will also need to consider similar issues eg. Do templates and static files reload?

**Comment by tomchristie** [comment]
Presumably we'd want to use `livereload`, as we already do with `mkdocs`...

https://github.com/mkdocs/mkdocs/blob/master/requirements/project.txt

Any other options? Pull requests welcome.

**Comment by tomchristie** [comment]
Django's runserver plus uses `watchman`

http://django-extensions.readthedocs.io/en/latest/runserver_plus.html#introduction

I believe we should go with that (as `livereload` has a dependancy on tornado, that I'd rather avoid)

Aside: Hadn't realised that flask's lovely debugging tools are actually part of werkzeug.
We should take advantage of that.

**Comment by jpadilla** [comment]
werkzeug has two backends for reloader support, the default is `stat` and the other one is [`watchdog`](https://pypi.python.org/pypi/watchdog) not [watchman](https://facebook.github.io/watchman/) as far as I remember.

**Comment by tomchristie** [comment]
Thanks @jpadilla! Been looking into it now.

**Comment by tomchristie** [comment]
We're not leveraging all the stuff that werkzeug provides right now either...
Eg. Using werkzeug request and response objects might be something we want to do.
