### ISSUE TITLE
i18n support

### ISSUE THREAD

**Issue by piotr-szpetkowski** [tomchristie/apistar#41]
I think that it would be great if internationalization could be provided out of the box without plugging in 3rd party solutions.

**Comment by tomchristie** [comment]
That'd be a way off right now, but possibly somewhere on the horizon yes.

**Comment by tomchristie** [comment]
Righty, so I'm going to close this off for now as being currently too far on the horizon to be actionable right now. Will we want this? In due course absolutely, yes. However for the time being we're better off concentrating on pre-requirements like customizable exception handling.
