### ISSUE TITLE
Benchmarking Changes

### ISSUE THREAD

**Issue by audiolion** [tomchristie/apistar#44]
Hey Tom, I was wondering about benchmarking the api performance on pull requests to see if they significantly affect the performance. Sort of like code coverage testing but against an API benchmark test instead. Just a thought!

**Comment by tomchristie** [comment]
At some point in the not too distant future let's consider something like this, yes. Perhaps eg once we've got the full suite of TechEmpower tests, rather than just the trivial hello, world.

**Comment by audiolion** [comment]
Refs #18 , should I close this issue for now?

**Comment by tomchristie** [comment]
Let's do, yes. I should probably adopt a policy of "open issue = actively on the radar". Things tend to get messy if we just keep open everything that we might do one day! :)
