### ISSUE TITLE
generic views and viewsets component

### ISSUE THREAD

**Issue by auvipy** [tomchristie/apistar#49]

**Comment by tomchristie** [comment]
We've got too many prerequisites right now that still need work before we can think about if we want to provide generic CRUD implementations.

If it *is* something that we end up doing then I certainly don't want to go down the class-based overriding route of Django & Django REST framework, as it's a great way for developers to overcomplicate their codebase.

Let's close this off for now, and come back to considering if it's something we want to provide for once we've got some of the more fundamental basics in place (eg. ORM support)
