### ISSUE TITLE
Managing multistage environment 

### ISSUE THREAD

**Issue by maziarz** [tomchristie/apistar#54]
In a multistage environment the requirements and settings are typically different. Lets take a database as an example. You cold be running in-memory for the local environment but PSQL for the others (development, staging and production), although on different servers. This would require fine-grain adjustment of the datasources. In LoopBack this is dealt by setting the `NODE_ENV` to which ever environment you'd like and setting the naming convention of the files accordingly. With basis in the datasources, `dataSources.json`, it would look like following:

```
// dataSources.json
// This is the default file where NODE_ENV is null
{
    "db": {
        "name": "db",
        "connector": "memory"
    }
}
```

```
// dataSources.development.js
// This is the development settings where NODE_ENV=development
module.exports = 
{
    db:  {
        "name": "db",
        "connector": "postgresql"
        "host": "some-destination-for-dev-database.com"
        ...
    }
}
```

```
// dataSources.production.js
// This is the production settings where NODE_ENV=production
module.exports = 
{
    db:  {
        "name": "db",
        "connector": "postgresql"
        "host": "some-destination-for-production-db.com"        
        ...
    }
}
```

Its very likely that this could be done in a more elegant way..

**Comment by tomchristie** [comment]
We will be following 12-factor style, yup, and have separate support for managing (1) the environment and (2) the settings.

**Comment by tomchristie** [comment]
Closing in favor of #83 and #84.
