### ISSUE TITLE
Preloading components

### ISSUE THREAD

**Issue by tomchristie** [tomchristie/apistar#67]
For components that don't rely on the incoming request, we generally want to preload them into the state, so that we don't end up recreating them on every incoming request.

In particular this is true right now for our templates, where we're naively recreating the jinja environment on every incoming request. The interface for templates is already correct, but we need to be preloading them behind the scenes.

**Comment by ciplazar** [comment]
The simplest naive implementation I can think of would be to do something like storing the return value of `build` in a class attribute and returning that if it's available. Something like this (components get cached the first time they're built):

```python
class Templates(jinja2.Environment):
    @classmethod
    def build(cls, settings: Settings):
        if hasattr(cls, 'cached'):
            return cls.cached
        template_dir = settings['TEMPLATES']['TEMPLATE_DIR']
        cls.cached = Templates(
            loader=jinja2.FileSystemLoader(template_dir)
        )
        return cls.cached
```

OR maybe something like this (components get cached when the app is initialized):

```python
class Templates(jinja2.Environment):
    @classmethod
    def cache(cls, settings: Settings):
        template_dir = settings['TEMPLATES']['TEMPLATE_DIR']
        cls.cached = Templates(
            loader=jinja2.FileSystemLoader(template_dir)
        )

    @classmethod
    def build(cls, settings: Settings):
        return cls.cached
```

And then in `App`'s `__init__` method we could do something like (assuming that all cacheable components need the `Settings` component):

```python
for component in cacheable_components:
    component.cache(self.settings)
```

**Comment by tomchristie** [comment]
@ciplazar That'd work yup! Although I'd actually like for components to be preloaded at the point of app instantiation, rather than at the point of "first time a view runs"

**Comment by ciplazar** [comment]
@tomchristie Thanks for the feedback! I think my second example above could satisfy that condition:

```python
class Templates(jinja2.Environment):
    @classmethod
    def cache(cls, settings: Settings):
        template_dir = settings['TEMPLATES']['TEMPLATE_DIR']
        cls.cached = Templates(
            loader=jinja2.FileSystemLoader(template_dir)
        )

    @classmethod
    def build(cls):
        return cls.cached
```

```python
class App(object):
    ...

    def __init__(self, routes=None, commands=None):
        ...
        try:
            for component in cacheable_components:
                component.cache(self.settings)
        except Something:
            raise ConfigurationError('...')
```

Unless I'm misunderstanding what you're going for.

**Comment by tomchristie** [comment]
Ah yup, that's true, with a couple of awkward provisos:

* Components which use the `ArgName` annotation in their build method.
* Ideally we'd like the components that we want to build to be automatically determined, based on whatever is routed, rather than a pre-specified set of components. The nice effect of that would be that third party components can be pre-loaded, and the app doesn't need to know anything about which components might or might not exists. We also get nice stuff like eg. Database components that only attempt to initialize if they're being used.

Having said that tho, I'm quite minded to introduce a stop-gap solution based on the above.
There's no great need for us to necessarily handle pre-loading `ArgName` components at this point, or any great harm in starting out with a pre-configured list of pre-loading components. Let's run with something simple for now, as it'll help keep us moving forward.

**Comment by tomchristie** [comment]
Alright, so as a first pass I'm going to get #90 merged.

That doesn't give us a general purpose approach to pre-loading components, and it doesn't allow us to preload all the way down to components such as `Template` which are based on the argument name, but it is sufficient for us to hard code a list of preloaded elements so that eg. we can instantiate our template environment and our database setup once and once only.

We'll move towards a dynamic solution in due course, which'll deal with *automatically* determining a list of component to load, rather than having a hard coded list.

**Comment by ciplazar** [comment]
@tomchristie Thanks for taking the time to give me detailed feedback on the idea!

> There's no great need for us to necessarily handle pre-loading ArgName components at this point, or any great harm in starting out with a pre-configured list of pre-loading components.

My thoughts exactly! I figured most components we'd want to preload at this stage (or, rather, that would need preloading the most) would probably just need the `Settings` object.
