### ISSUE TITLE
Interactive API Documentation

### ISSUE THREAD

**Issue by tomchristie** [tomchristie/apistar#71]
We'll be pulling in REST framework's existing interactive API docs.
It's gonna be ✨fabulous✨.

**Comment by apollo13** [comment]
@tomchristie Given that apistar knows about input (and output) schemas it would be really great if the documentation would show those schemas -- this way a consumer of the api would know what to provide and what to expect.

**Comment by audiolion** [comment]
Agreed, though I found myself struggling with the Schemas, mostly because to do them on a response you have to basically reprocess the entire response through them. e.g.

```
# schemaless
def get_data():
    return Model.objects.all()

# with schema, seems like it could have performance implications
def get_data() -> Array[ModelSchema]:
    return [ModelSchema(record) for record in Model.objects.all()]  
```

If some of the validations are complex wouldn't this add a lot of overhead to the response time?

My question is, if I know the source and know it will follow the contract because of validating before it went into the database, why check it on the way back out if I am not mutating it in any way?

**Comment by apollo13** [comment]
Your code example is something that could be fixed. Imo
```
return Model.objects.all()
```
should be enough and `Array[ModelSchema]` should handle the rest.

> If some of the validations are complex wouldn't this add a lot of overhead to the response time?

Probably, but then again you usually cannot serialize model objects 1:1 anyways (ie password field of user). That said, for response it might be okay if you just use the schema as serializer hints, not really run the validation (or at least make it optional).

Either way, having a Schema to describe input/output (maybe even generate a swagger schema from it) would be nice.

**Comment by audiolion** [comment]
Yeah, I figured `return Model.objects.all()` might work but I wasn't sure. I think I would like the idea of being able to create the Schemas and use the annotated functions to generate schema docs based on the responses.

```python

# schemaless, no annotation, no special docs
def get_data():
    return Model.objects.all()

# includes annotation of schema, docs use annotation to display the spec for the response (or input)
def get_data() -> Array[ModelSchema]:
    return Model.objects.all()

# includes schema for validation and annotation
def get_data() -> Array[ModelSchema]:
    return [ModelSchema(record) for record in Model.objects.all()]
```

That way, if the developer takes the time to write the schemas  and annotate they get the docs benefit without the overhead if they do not need the validation.

**Comment by tomchristie** [comment]
> Given that apistar knows about input (and output) schemas it would be really great if the documentation would show those schemas -- this way a consumer of the api would know what to provide and what to expect.

@apollo13 - Absolutely yup, that's coming.

> If some of the validations are complex wouldn't this add a lot of overhead to the response time?

Model instances wouldn't be JSON serializable as-is, so you need *some* transformation there whatever. And sure, we'll be making sure that's as minimal overhead as possible.

**Comment by tomchristie** [comment]
Not sure why this ticket never got closed off, since we *do* have this now.
Clearly some refinements still to make, but those should get followed up against more specific tickets.
