### ISSUE TITLE
Routing

### ISSUE THREAD

**Issue by tomchristie** [tomchristie/apistar#77]
Still some bits to do:

* URL Reversing
* Support `include`, and create sections in API schemas/docs.
* Figure out hostname binding (eg. search for example.com in our codebase)
* Path components
* Remove `URLPathArg` guard if `URLPathArgs` is used.

**Comment by sandys** [comment]
DRF has a very public stand against nested routing. I'm not sure what is wrong or right, but for people *migrating* to a new framework (like Apistar), nested routes is a must have. Especially when you have live mobile apps, it is impossible to correct mistakes in early API design. 

Would you support nested routes in apistar?

**Comment by tomchristie** [comment]
The difficulties with nested routing in REST framework are more around how the generically provided bits of behavior (ie. the generic views) would work in that case, and also around how you handle automatic hyperlinking in that case.

We won't be planning on bringing in quite so much automagical generic behavior into API Star, so yes you're absolutely free to structure the API however you wish.

There is one thing related to this where API Star will be able to do a better job than REST framework currently does, which is about how nested URLs get handled in schema generation, schema layout, and API docs. That's difficult in REST framework since we have to automagically infer what schema layout would work well. In API Star that'll be built into the structure of the application itself. (Eg. using "includes" to create new sections within a schema)

**Comment by sandys** [comment]
This is awesome!
Is the nested routes currently available or is it a future plan ? Only reason I ask is because your examples are the simpler, single level routes.

**Comment by tomchristie** [comment]
We don't have 'includes' but you can structure the URL layout however you want, yes.

**Comment by tomchristie** [comment]
We have all the functionality listed here now.
