### ISSUE TITLE
Parsing

### ISSUE THREAD

**Issue by tomchristie** [tomchristie/apistar#79]
Right now we're hardwiring in JSON. We'll want to change that and add proper content negotiation.

**Comment by maziarz** [comment]
Support for multipart data

**Comment by tomchristie** [comment]
Werkzeug has great support for handling this, so we'll rely on that.

**Comment by maziarz** [comment]
That would be great. Seems to get the job done quite well!

**Comment by tomchristie** [comment]
De-scoping this to just parsing for now.

**Comment by qwIvan** [comment]
Doesn't validate if field is None?
